version: 2.1

orbs:
  anchore: anchore/anchore-engine@dev:0.1.3

workflows:
  scan_image:
    jobs:
      - anchore/image_scan:
          image_name: "btodhunter/anchore-engine:latest"
          private_registry: True
          registry_name: docker.io
          registry_user: $DOCKERHUB_USER
          registry_pass: $DOCKERHUB_PASSWORD
